### ISSUE TITLE
Add Github action to support CI/CD for Github Package

### ISSUE THREAD

**Issue by dalenguyen** [dalenguyen/typescript-package-starter#1]
This is a GitHub package starter. It would be great if it can support CI/CD process through Github Actions.

When there is an update to the package, the CI/CD will initiate and deploy to Github package. Make sure that the test is passed.

Thanks,

**Comment by honsq90** [comment]
I'd be keen to give this a go if that's okay?

**Comment by dalenguyen** [comment]
@honsq90 Yes, please go ahead :)
